-- ============================================================
-- Learning Logs Database — Sample Data (Week 10)
-- ============================================================
-- Run this file AFTER learninglog.sql to add sample data.
--
-- Uses DATE_SUB(NOW(), INTERVAL n DAY) for created_at so that
-- dashboard analytics (Topics This Week, Entries Today, etc.)
-- show meaningful non-zero values on first run.
--
-- NOTE: Passwords below are BCrypt hashes of "Test@123"
-- (generated by PasswordUtil.getHashPassword("Test@123"))
-- In a real app, passwords are NEVER stored as plaintext.
-- ============================================================

USE learning_logs;

-- Clear existing data before seeding
DELETE FROM entries;
DELETE FROM topics;
DELETE FROM users;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE topics AUTO_INCREMENT = 1;
ALTER TABLE entries AUTO_INCREMENT = 1;

-- ========== Users ==========
-- Two test users for verifying topic isolation
-- Both use password: "Test@123"
INSERT INTO users (username, email, password) VALUES
('testuser', 'test@example.com', '$2a$10$yUK8SPXB.NwRSviTxcIVHOxtfvwjGEe600j9g2H5xi3Y4l54A5jLa'),
('demouser', 'demo@example.com', '$2a$10$yUK8SPXB.NwRSviTxcIVHOxtfvwjGEe600j9g2H5xi3Y4l54A5jLa');

-- ========== Topics ==========
-- testuser (id=1) has 5 topics — spread across last 12 days
-- so "Topics This Week" shows a subset, not all
INSERT INTO topics (name, user_id, created_at) VALUES
('Python', 1, DATE_SUB(NOW(), INTERVAL 12 DAY)),
('Web Development', 1, DATE_SUB(NOW(), INTERVAL 10 DAY)),
('Data Science', 1, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('Machine Learning', 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('Cybersecurity', 1, DATE_SUB(NOW(), INTERVAL 1 DAY));

-- demouser (id=2) has 3 topics
INSERT INTO topics (name, user_id, created_at) VALUES
('Java', 2, DATE_SUB(NOW(), INTERVAL 11 DAY)),
('Databases', 2, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Cloud Computing', 2, DATE_SUB(NOW(), INTERVAL 2 DAY));

-- ========== Entries ==========
-- testuser's entries (topics 1-5) — spread across last 7 days
-- At least 1-2 entries use NOW() so "Entries Today" shows non-zero
INSERT INTO entries (topic_id, title, text, link, image, created_at) VALUES
(1, 'Variables and Data Types', 'Python uses dynamic typing. Variables do not need explicit type declarations.', 'https://docs.python.org/3/tutorial/introduction.html', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 6 DAY)),
(1, 'Control Flow', 'if/elif/else statements and for/while loops are the main control flow tools in Python.', 'https://docs.python.org/3/tutorial/controlflow.html', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 5 DAY)),
(2, 'HTML Basics', 'HTML provides the structure of a web page using elements and tags.', 'https://developer.mozilla.org/en-US/docs/Learn/HTML', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 5 DAY)),
(2, 'CSS Flexbox', 'Flexbox is a one-dimensional layout method for arranging items in rows or columns.', 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 4 DAY)),
(3, 'Introduction to Pandas', 'Pandas provides DataFrames for structured data analysis in Python.', 'https://pandas.pydata.org/docs/', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(3, 'Data Visualization with Matplotlib', 'Matplotlib is a plotting library for creating static, animated, and interactive visualizations.', 'https://matplotlib.org/stable/tutorials/index.html', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(4, 'What is Machine Learning?', 'Machine learning is a subset of AI where systems learn from data to improve performance without being explicitly programmed.', 'https://developers.google.com/machine-learning/crash-course', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(4, 'Supervised vs Unsupervised Learning', 'Supervised learning uses labeled data for training, while unsupervised learning finds patterns in unlabeled data.', 'https://scikit-learn.org/stable/tutorial/index.html', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(5, 'Network Security Fundamentals', 'Understanding firewalls, encryption, and secure protocols is the foundation of cybersecurity.', 'https://www.cisco.com/c/en/us/products/security/what-is-network-security.html', 'static/images/book.png', NOW()),
(5, 'Common Web Vulnerabilities', 'OWASP Top 10 covers the most critical web application security risks including XSS, SQL injection, and CSRF.', 'https://owasp.org/www-project-top-ten/', 'static/images/book.png', NOW());

-- demouser's entries (topics 6-8) — spread across last 7 days
INSERT INTO entries (topic_id, title, text, link, image, created_at) VALUES
(6, 'OOP Concepts', 'Java is an object-oriented language with classes, inheritance, and polymorphism.', 'https://docs.oracle.com/javase/tutorial/java/concepts/', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 6 DAY)),
(6, 'Exception Handling', 'Java uses try-catch-finally blocks to handle runtime errors gracefully without crashing the program.', 'https://docs.oracle.com/javase/tutorial/essential/exceptions/', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 4 DAY)),
(7, 'SQL Basics', 'SQL is used to communicate with relational databases using SELECT, INSERT, UPDATE, DELETE.', 'https://www.w3schools.com/sql/', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(7, 'Database Normalization', 'Normalization organizes database tables to reduce redundancy and improve data integrity through normal forms (1NF, 2NF, 3NF).', 'https://www.guru99.com/database-normalization.html', 'static/images/book.png', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(8, 'What is Cloud Computing?', 'Cloud computing delivers computing services like servers, storage, and databases over the internet on a pay-as-you-go basis.', 'https://azure.microsoft.com/en-us/overview/what-is-cloud-computing/', 'static/images/book.png', NOW()),
(8, 'IaaS vs PaaS vs SaaS', 'Infrastructure, Platform, and Software as a Service represent different levels of cloud abstraction — from managing VMs to using ready-made apps.', 'https://cloud.google.com/learn/paas-vs-iaas-vs-saas', 'static/images/book.png', NOW());
